### ISSUE TITLE
does not working at all - unknown errors

### ISSUE THREAD

**Issue by asdnsc** [idammi/blob-video-downloader#1]
Security Error: Content at https://*****.com/am/f/063781 may not load data from blob:https://****.com/-68b6-40cd-b5c0-41cbac94b219.
Error downloading video: TypeError: NetworkError when attempting to fetch resource.
    <anonymous> debugger eval code:14
    <anonymous> debugger eval code:28

If I click on error code to see explanation then new window poup up with no web address saying: ooops something is wrong....

Aside of this - video keeps playing.

**Comment by idammi** [comment]
Can you try opening the link to the video directly in your browser, then try using the code on the tab that has the actual video playing and give your feedback here

**Comment by Pysis868** [comment]
Not blob links, and no other direct link to easily find

```
Security Error: Content at https://www.facebook.com/<username>/videos/#?idorvanity=# may not load data from blob:https://www.facebook.com/.-.-.-.-.

Error downloading video: TypeError: NetworkError when attempting to fetch resource.
    <anonymous> debugger eval code:16
    <anonymous> debugger eval code:30
[debugger eval code:29:29](chrome://devtools/content/webconsole/debugger%20eval%20code)
    <anonymous> debugger eval code:29
    (Async: promise callback)
    <anonymous> debugger eval code:29
    <anonymous> debugger eval code:30
```
